In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def sigmoid(array:np.array) -> np.array:
    return 1/(1+np.exp(-array))

def generate_parameters():
    parameters={}
    for pos in range(n_layers-1):
        parameters[f'w{pos+1}'] = np.random.rand(nodes[pos+1], nodes[pos])-0.5
        parameters[f'b{pos+1}'] = np.random.rand(nodes[pos+1], 1)-0.5
    return parameters

In [61]:
def forward_prop(x_input, parameter):
    a=x_input
    nodes_values[f'l{1}']=a
    print('FORWARD PASS'+'-'*10)
    for pos in range(1,n_layers):
        w = parameter[f'w{pos}']
        b=parameter[f'b{pos}']
        z=np.dot(w,a)+b
        a=sigmoid(z)
        print(f'z{pos+1}=w{pos}.a{pos}+b{pos}')
        print(f'a{pos+1}=sigmoid(z{pos+1})')
        nodes_values[f'l{pos+1}']=a
    print('forward pass ends ----')
    return a


In [62]:
def back_prop(parameters, y_true, y_pred):
    delta = (nodes_values[f'l{n_layers}']-y_true)
    delta_para={}
    print('-'*4+'BACK PROP STARTS'+'-'*6)
    print(f'delta{n_layers}=l{n_layers}-y_true')

    delta_para[f'delW{n_layers-1}']=np.dot(delta, nodes_values[f'l{n_layers-1}'].T)*lr/m
    delta_para[f'delB{n_layers-1}']=(np.sum(delta, axis=1, keepdims=True))*lr/m

    print(f'dW{n_layers-1}=(delta{n_layers}.a{n_layers-1}T)*lr/m')
    print(f'db{n_layers-1}=(sum(delta{n_layers}))*lr/m')

    for pos in range(n_layers-1,1,-1):
        a=nodes_values[f'l{pos}']
        x=nodes_values[f'l{pos-1}']
        delta=np.dot(parameters[f'w{pos}'].T, delta)*((a)*(1-a))

        print(f'delta{pos}=(w{pos}T).delta{pos+1}x(a{pos})*(1-a{pos})')

        delta_para[f'delW{pos-1}']=np.dot(delta, x.T)*lr/m
        delta_para[f'delB{pos-1}']=np.sum(delta, axis=1, keepdims=True)*lr/m

        print(f'dW{pos-1}=delta{pos}.a{pos-1}T')
        print(f'dB{pos-1}=delta{pos}.ones')
    print('BACK PROP ENDSSS', 'X'*9)
    return delta_para

In [63]:
def update_parameters(parameters, delta_para):
    for pos in range(n_layers-1,0,-1):
        parameters[f'w{pos}']-=delta_para[f'delW{pos}']
        parameters[f'b{pos}']-=delta_para[f'delB{pos}']
    return parameters



In [64]:
def cost(y_hat, y):
    value=y*np.log(y_hat)+(1-y)*np.log(1-y_hat)
    cost_val=np.sum(value)
    return -cost_val/m

In [65]:
global nodes_values
nodes=[784,30,20,26]
lr=0.3
nodes_values = {}
n_layers=len(nodes)

In [66]:
file_path = '/content/drive/MyDrive/cyberlabs_google_colab/Colab Notebooks/emnist-letters-train.csv'
df=pd.read_csv(file_path)
x_train=df.iloc[:,1:785]
y_train=df[['23']]
m=y_train.shape[0]
x_train = np.array(x_train).T/255
y_train = np.array(y_train)

In [67]:
multi_class_y_train=[]
for element in y_train:
    element = int(element)
    value = (0,)*(element-1)+(1,)+(0,)*(26-element)
    multi_class_y_train.append(value)
multi_class_y_train = np.array(multi_class_y_train).T


In [69]:
iter_pos=0
max_iter=2
iter_cost=[]
parameters=generate_parameters()
while iter_pos<max_iter:
    y_pred = forward_prop(x_train, parameters)
    cost_value = cost(y_hat=y_pred, y=multi_class_y_train)
    iter_cost.append(cost_value)

    delta_para = back_prop(parameters, multi_class_y_train, y_pred)
    parameters=update_parameters(parameters,delta_para)

    print('--0'*(20))
    print(iter_pos, cost_value)
    iter_pos+=1
    


FORWARD PASS----------
z2=w1.a1+b1
a2=sigmoid(z2)
z3=w2.a2+b2
a3=sigmoid(z3)
z4=w3.a3+b3
a4=sigmoid(z4)
forward pass ends ----
----BACK PROP STARTS------
delta4=l4-y_true
dW3=(delta4.a3T)*lr/m
db3=(sum(delta4))*lr/m
delta3=(w3T).delta4x(a3)*(1-a3)
dW2=delta3.a2T
dB2=delta3.ones
delta2=(w2T).delta3x(a2)*(1-a2)
dW1=delta2.a1T
dB1=delta2.ones
BACK PROP ENDSSS XXXXXXXXX
--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0
0 16.360349462569392
FORWARD PASS----------
z2=w1.a1+b1
a2=sigmoid(z2)
z3=w2.a2+b2
a3=sigmoid(z3)
z4=w3.a3+b3
a4=sigmoid(z4)
forward pass ends ----
----BACK PROP STARTS------
delta4=l4-y_true
dW3=(delta4.a3T)*lr/m
db3=(sum(delta4))*lr/m
delta3=(w3T).delta4x(a3)*(1-a3)
dW2=delta3.a2T
dB2=delta3.ones
delta2=(w2T).delta3x(a2)*(1-a2)
dW1=delta2.a1T
dB1=delta2.ones
BACK PROP ENDSSS XXXXXXXXX
--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0--0
1 8.20582319238496


In [53]:
y_hat=forward_prop(x_train, parameters).T
y_hat[0:5]

array([[0.08301952, 0.03863324, 0.0280795 , 0.00854853, 0.08585228,
        0.03215856, 0.03194675, 0.03864083, 0.02951436, 0.03932889,
        0.00669167, 0.00369602, 0.01768954, 0.0089619 , 0.10505831,
        0.02039739, 0.0763707 , 0.01285466, 0.01975995, 0.01548721,
        0.01807082, 0.01602991, 0.02570838, 0.04788176, 0.06527615,
        0.01332654],
       [0.01059378, 0.03221194, 0.0129849 , 0.02818418, 0.02072546,
        0.01468732, 0.01181744, 0.02540153, 0.0099566 , 0.01170247,
        0.0547894 , 0.00869427, 0.02307905, 0.01916745, 0.00515808,
        0.0267166 , 0.04682901, 0.02085509, 0.00566329, 0.01911016,
        0.02318451, 0.05776348, 0.01117047, 0.06450263, 0.01412838,
        0.02317453],
       [0.02889291, 0.05831611, 0.0147858 , 0.01320849, 0.00701056,
        0.00424424, 0.08818394, 0.0258249 , 0.015071  , 0.05102098,
        0.01186644, 0.00316112, 0.07434196, 0.01182641, 0.03339501,
        0.01551203, 0.02412724, 0.00698965, 0.10069891, 0.01955592,
      

In [56]:
pos=0
y_hat=forward_prop(x_train, parameters).T
print(y_hat.shape, y_train.shape)

correct=0
wrong=0
for row in y_hat:

    row=list(np.round(row))
    prediction=row.index(max(row))+1
    true_val=y_train[pos]
    print(prediction, true_val)
    if prediction==true_val:
        correct+=1

    else:
        wrong+=1
    pos+=1
print(correct/(wrong+correct))

Streaming output truncated to the last 5000 lines.
1 [16]
1 [16]
1 [6]
1 [25]
1 [21]
1 [19]
1 [9]
1 [1]
1 [8]
1 [17]
1 [9]
1 [10]
1 [20]
1 [16]
1 [8]
1 [13]
1 [5]
1 [15]
1 [2]
1 [8]
1 [25]
1 [13]
1 [25]
1 [19]
1 [8]
1 [4]
1 [20]
1 [12]
1 [21]
1 [6]
1 [25]
1 [24]
1 [9]
1 [1]
1 [1]
1 [1]
1 [4]
1 [2]
1 [19]
1 [8]
1 [25]
1 [11]
1 [4]
1 [10]
1 [1]
1 [25]
1 [4]
1 [11]
1 [19]
1 [11]
1 [23]
1 [12]
1 [24]
1 [2]
1 [21]
1 [19]
1 [3]
1 [24]
1 [18]
1 [7]
1 [5]
1 [12]
1 [16]
1 [16]
1 [19]
1 [26]
1 [9]
1 [10]
1 [18]
1 [11]
1 [26]
1 [22]
1 [7]
1 [10]
1 [11]
1 [7]
1 [6]
1 [17]
1 [17]
1 [18]
1 [21]
1 [8]
1 [20]
1 [18]
1 [17]
1 [1]
1 [16]
1 [16]
1 [21]
1 [24]
1 [1]
1 [5]
1 [7]
1 [10]
1 [17]
1 [21]
1 [19]
1 [7]
1 [9]
1 [9]
1 [7]
1 [12]
1 [2]
1 [14]
1 [16]
1 [6]
1 [19]
1 [9]
1 [14]
1 [6]
1 [1]
1 [3]
1 [21]
1 [22]
1 [16]
1 [23]
1 [18]
1 [10]
1 [3]
1 [8]
1 [6]
1 [4]
1 [3]
1 [1]
1 [23]
1 [7]
1 [16]
1 [23]
1 [22]
1 [15]
1 [19]
1 [26]
1 [8]
1 [9]
1 [10]
1 [23]
1 [15]
1 [1]
1 [23]
1 [8]
1 [8]
1 [20]
1 [4]
1 [13]

KeyboardInterrupt: ignored

In [ ]:
for i in range(0,20)

delB3 (26, 1)
delW2 (20, 784)
delB2 (20, 1)


In [ ]:
y_pred = forward_prop(x_train, parameters)
y_pred.T[0:4]

array([[0.02384042, 0.03059066, 0.02677563, 0.04757088, 0.02593967,
        0.04087975, 0.03252238, 0.02808012, 0.02459956, 0.0351299 ,
        0.02714427, 0.03669332, 0.02564039, 0.03287116, 0.04517948,
        0.03831486, 0.05463028, 0.04132493, 0.03581857, 0.03984185,
        0.04347261, 0.04923115, 0.03445783, 0.04570023, 0.03272753,
        0.03723047],
       [0.06441242, 0.0402313 , 0.08473456, 0.04667365, 0.06068491,
        0.06714205, 0.07163624, 0.03343253, 0.05135003, 0.03825846,
        0.04493157, 0.04675958, 0.04586885, 0.03641419, 0.02434696,
        0.05831954, 0.08490992, 0.05529441, 0.03607499, 0.0415765 ,
        0.05658803, 0.06062745, 0.03742365, 0.04633029, 0.07382299,
        0.05346607],
       [0.02392171, 0.03409882, 0.02841321, 0.05852129, 0.03234573,
        0.05008771, 0.04091148, 0.03819085, 0.02669562, 0.04166005,
        0.02845911, 0.03474509, 0.02623501, 0.03627973, 0.0477805 ,
        0.0387775 , 0.05425911, 0.0513548 , 0.0397188 , 0.0520384 ,
      

In [ ]:
y_train_hat=forward_prop(x_train, parameters)

In [ ]:
y_train_hat[0:2]

array([[0.0473869 , 0.0473869 , 0.0473869 , ..., 0.0473869 , 0.0473869 ,
        0.0473869 ],
       [0.03387416, 0.03387416, 0.03387416, ..., 0.03387416, 0.03387416,
        0.03387416]])

In [ ]:
m=4
cost(np.array([[1,1,1,1]]).T,np.array([[1,1,1,1]]))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  


nan

In [ ]:
neural_parameters=parameters

In [ ]:
parameters['w4']

array([[-0.01055357, -0.32285503, -0.41710368, ...,  0.03574653,
        -0.2231155 , -0.13078533],
       [ 0.17682451,  0.34331155, -0.22992491, ..., -0.34121201,
         0.23087246,  0.21173801],
       [ 0.32991154,  0.30589368, -0.40121103, ..., -0.26108367,
         0.2858601 ,  0.38069274],
       ...,
       [-0.2315624 , -0.07534071,  0.15852992, ..., -0.20821695,
         0.17830426,  0.10254992],
       [-0.50424367, -0.14742367, -0.05896797, ...,  0.07893041,
        -0.22924825,  0.23070668],
       [-0.57263342,  0.01893274, -0.42440528, ...,  0.4213423 ,
         0.16176473, -0.16720894]])

In [ ]:
file_path = '/content/drive/MyDrive/cyberlabs_google_colab/Colab Notebooks/emnist-letters-test.csv'
df=pd.read_csv(file_path)
x_test=df.iloc[:,1:785]
y_test=df[['1']]
m=y_train.shape[0]
x_test = np.array(x_test).T/255
y_test = np.array(y_test)

In [ ]:
pos=0
y_hat=forward_prop(x_test, parameters).T
print(y_hat.shape, y_test.shape)
# print(y_hat.shape,y_hat[0],y_hat[1])

correct=0
wrong=0
for row in y_hat:
    row=list(np.round(row))
    prediction=row.index(max(row))+1
    true_val=y_test[pos]
    if prediction==true_val:
        correct+=1
        print(prediction, true_val)

    else:
        wrong+=1
    pos+=1
    if pos>9:
        break
    # print(true_val, prediction)
print(correct/(wrong+correct))


(14799, 26) (14799, 1)
1 [1]
1 [1]
1 [1]
1 [1]
1 [1]
1 [1]
1 [1]
1 [1]
1 [1]
1 [1]
1.0


In [ ]:
import pickle 
f=open('/content/drive/MyDrive/cyberlabs_google_colab/Colab Notebooks/neural_parameters.dat', 'wb')
pickle.dump(neural_parameters, f)
f.close()

In [ ]:
# f2=open('/content/drive/MyDrive/cyberlabs_google_colab/Colab Notebooks/neural_parameters.dat', 'rb')
# data=pickle.load(f2)
# print(data)

dick head


(3, 1)
(3, 1)


array([[-2],
       [-1],
       [ 0]])